#use_frameworks!
platform :ios, '8.0'
target 'MAPreviewControllerDemo' do
  pod 'MAPreviewController', :path => '../'
  #pod 'MAPreviewController', :git => 'https://github.com/fengyunjue/MAPreviewController.git'

end
